version: "3.9"

services:
  api:
    image: livechrg-api
    ports:
      - "8080:8080"
    networks:
      - api_network
    environment:
      PG_HOST: pg
      PG_PORT: 5432
      PG_USER: livechrg-api
      PG_PASSWORD: livechrg-api  # change on production
      PG_DATABASE: livechrg-api
      ADMIN_AUTH_TOKEN: token  # change on production
    depends_on:
      pg:
        condition: service_started
      migrate:
        condition: service_completed_successfully

  migrate:
    image: migrate/migrate
    networks:
      - api_network
    volumes:
      - ./migrations:/migrations
    command: [
      "-path",
      "/migrations",
      "-database",
      "postgres://livechrg-api:livechrg-api@pg:5432/livechrg-api?sslmode=disable",
      "up"
    ]   # change on production
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgis/postgis:14-3.3-alpine
    ports:
      - "5433:5432"
    networks:
      - api_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: livechrg-api
      POSTGRES_PASSWORD: livechrg-api  # change on production
      POSTGRES_DB: livechrg-api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U livechrg-api" ]
      interval: 5s
      timeout: 5s
      retries: 3

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - 5601:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

networks:
    api_network:

volumes:
  postgres-data:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local