  name: ci

  on:
    pull_request:
      branches: [ master ]

    push:
      branches: [ ci ]

  jobs:
    ci:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Install poetry
          uses: snok/install-poetry@v1

        - name: Install dependencies
          run: poetry install --no-interaction --no-root

        - name: Install PostGIS
          uses: nyurik/action-setup-postgis@v1
          with:
            username: livechrg-api
            password: sw0rdfish
            database: livechrg-api
            port: 5437
          id: pg

        - name: Run linter
          run: poetry run ruff check .

        - name: Run unit tests
          run: poetry run pytest -v tests

        - name: Install golang-migrate
          run: |
            curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz;
            sudo mv migrate /usr/bin/migrate;
            which migrate

        - name: Apply migrations
          run: migrate -path ./migrations -database "postgres://livechrg-api:livechrg-api@localhost:5437/livechrg-api?sslmode=disable" up
          env:
            POSTGRES_USER: livechrg-api
            POSTGRES_PASSWORD: livechrg-api
            POSTGRES_PORT: 5437
            POSTGRES_DB: livechrg-api

        - name: Run functional tests
          run: poetry run pytest -v tests_functional